### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by woutf** [mdawsonuk/streamdeck-agh#26]
Hi,

The plugin isn't working for me anymore. I've added it to the Stream Deck and when I press the test button I get the 'Success!' message. But I then want to toggle the AdGuard protection, nothing happens. In the AdGuard logs I can see this pop up

`POST 192.168.1.127:83 /control/dns_config: only content-type application/json is allowed`

Might have something to do with this? https://github.com/AdguardTeam/AdGuardHome/issues/4970

**Comment by mdawsonuk** [comment]
Hey,

Thanks for letting me know! I'll look into fixing this this weekend.

**Comment by mdawsonuk** [comment]
This should be fixed in v0.2.1 @woutf - thanks for the bug report 🙂
